### ISSUE TITLE
Open Subtitle instead or with Yify Subtitles

### ISSUE THREAD

**Issue by snisnik** [carlelieser/flixerr#26]
There is a particular reason why you use yify subtitles instead of open subtitles?
There are a lot of movies that do not have subtitles this way.
Maybe using open subtitles too can fix it? Just a suggestion.

**Comment by carlelieser** [comment]
Originally I used Yify because Open Subtitles had a weird, not very well documented api and Yify let me scrape their site pretty easily. I just looked up Open Subtitles API and it looks like it’s pretty easy to use and I can even get subtitles anonymously which is a plus so I’ll definitely take a look into this!

**Comment by RadGade** [comment]
I found a great npm package for it too https://www.npmjs.com/package/opensubtitles-api.

**Comment by RadGade** [comment]
I would start working on it but my charger for my surface pro died, so :(

**Comment by carlelieser** [comment]
> I found a great npm package for it too https://www.npmjs.com/package/opensubtitles-api.

Yeah that’s the one I looked at!

**Comment by carlelieser** [comment]
Going to close this one because opensubtitles is a bitch and a half.
